### ISSUE TITLE
Hand failed to execute

### ISSUE THREAD

**Issue by marcelpanse** [marcelpanse/roborally#105]
The feedback from Fred on April 6th 2015 was:

> Had a bug where my hand didn't execute at all.
> Just before that happened, I played a u-turn on the last phase of my previous turn. It didn't look like the u-turn executed to me, so i refreshed the page to see if it was just my robot's direction that didn't update. My robot was still facing the same way, so I just programmed my hand from there. That's the hand that didn't execute. 
> 
> Otherwise, it looks really good! Let me know if I could help with testing.

View it on [Doorbell](https://doorbell.io/applications/970/feedback/12492)

**Comment by shiona** [comment]
We had the same problem twice in one game. 
![screenshot-7](https://cloud.githubusercontent.com/assets/1516312/7011378/2aa021e0-dcb1-11e4-8f6c-d765310140f8.png)
![screenshot-8](https://cloud.githubusercontent.com/assets/1516312/7011377/2aa008b8-dcb1-11e4-868a-effc132e484a.png)

It's noteworthy that one u-turn I played did work correctly,

**Comment by xithan** [comment]
I don't observe any problems with u-turns. I guess it's a problem with the card with the lowest priority in the deck (which is a u-turn)
