### ISSUE TITLE
Robots refuse to move forward!

### ISSUE THREAD

**Issue by Shimrath** [marcelpanse/roborally#31]
Hello,

Played in two games today ("play?' and "try again!").  The first game, my opponent got stuck at the edge of the conveyor belt.  I offered to restart the game and then we both got stuck in one spot, unable to move forward.  I even played five "move forward 1" cards in a single turn to test, and the robot spun around, but did not move.

**Comment by marcelpanse** [comment]
Thanks for the bugreport, we drastically rewrote most part of the game, this bug is not reproducible in the new version (not live yet), so I'll close it.
