### ISSUE TITLE
Player feedback

### ISSUE THREAD

**Issue by marcelpanse** [marcelpanse/roborally#92]
The feedback from maska@cvx.fi on March 29th 2015 was:

> The new GUI improvements are great. The register phases play a bit too slow to watch and wait to go by and the translucrent register phase infobox covers the map a bit too much, though.
> 
> I just found a new show-stopping bug. I was able to select two cards for a single register. I have a slow laptop and I clicked on two cards very quickly. They went into the same register and one of them disappeared. I couldn't take it out (wasn't there) or put it back in (was disabled).
> 
> After the card disappeared, my bot was unable to move. I could select cards for my registers and play normally. Except the bot would not execute the registers. It would reveal the first card and then do nothing, while my opponent moved around freely and its bot revealed its cards. At the end of the turn, I would have just my first card revealed and my opponent all of his.
> 
> There is also a bug where taking enough damage to have the 5th register locked for the first time makes the 5th card disappear instead of being locked. The next turn I couldn't fill my registers and had to wait for the countdown, because I had only 4 cards for 5 registers. When the time ran out, my bot just played 4 registers and skipped the last one that had no card.

View it on [Doorbell](https://doorbell.io/applications/970/feedback/11387)

**Comment by marcelpanse** [comment]
The phases display is work in progress and I totally agree it is too invasive at the moment. I'll change that soon so I don't take up so much space.

**Comment by shiona** [comment]
This is how the 4-cards-only situation looked for me as an opponent.

![screenshot](https://cloud.githubusercontent.com/assets/1516312/6885958/0b2c074c-d636-11e4-8b36-fbcf5965034b.png)

**Comment by shiona** [comment]
After some testing this seems to be clearly a synchronization problem. Over a laggy network quickly selecting/removing cards repatedly resulted in the following situation on the first turn.
![screenshot-4](https://cloud.githubusercontent.com/assets/1516312/6886730/e7de79ee-d650-11e4-9841-dcfffbbf9c70.png)

**Comment by marcelpanse** [comment]
GUI is improved and Card selection bug is fixed. I will test this soon and deploy it to the server.
