### ISSUE TITLE
don't hide board when game is over

### ISSUE THREAD

**Issue by xithan** [marcelpanse/roborally#95]

**Comment by marcelpanse** [comment]
@xithan why do you want to show the board? 
Maybe it is more fun to show some statistics about the game, like 
nr of players, number of cards played, game length in minutes..

**Comment by xithan** [comment]
I want to see how the game ended, where the other players were, who was close to win. I had a 6 player game in which me and other players didn't notice that somebody was winning and suddenly the game disappeared and we didn't know what happened.
